apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dynatrace
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dynatrace
  # source:
  #   repoURL: https://raw.githubusercontent.com/Dynatrace/dynatrace-operator/main/config/helm/repos/stable
  #   targetRevision: 0.15.0

  #   chart: dynatrace-operator
  #   helm:
  #     valuesObject:
  #       installCRD: true

  #       csidriver:
  #         enabled: true

  sources:
  - repoURL: https://raw.githubusercontent.com/Dynatrace/dynatrace-operator/main/config/helm/repos/stable
    chart: dynatrace-operator
    targetRevision: 0.15.0
    helm:
      valueFiles:
      - $values/argocd/values.yaml
  - repoURL: https://github.com/martinnirtl/dynatrace.git
    targetRevision: HEAD
    ref: values
  # - repoURL: https://github.com/martinnirtl/dynatrace.git
  #   targetRevision: HEAD
  #   path: argocd/dynakube.yaml

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
